### ISSUE TITLE
ldbc/datagen:latest from Docker Hub fails to start

### ISSUE THREAD

**Issue by thSoft** [ldbc/ldbc_snb_datagen_spark#109]
Running datagen using the latest image from Docker Hub fails:

```
$ docker run --rm --mount type=bind,source="$(pwd)/",target="/opt/ldbc_snb_datagen/out" --mount type=bind,source="$(pwd)/params.ini",target="/opt/ldbc_snb_datagen/params.ini" ldbc/datagen
Unable to find image 'ldbc/datagen:latest' locally
latest: Pulling from ldbc/datagen
092586df9206: Pull complete 
ef599477fae0: Pull complete 
4530c6472b5d: Pull complete 
d34d61487075: Pull complete 
272f46008219: Pull complete 
12ff6ccfe7a6: Pull complete 
f26b99e1adb1: Pull complete 
6477fd664e3c: Pull complete 
309431816e80: Pull complete 
4e7b9cf72945: Pull complete 
ef94afabc02c: Pull complete 
fdb23ae508a4: Pull complete 
7e478e4997d5: Pull complete 
d02c217b7071: Pull complete 
c90f56406a3f: Pull complete 
02c8aa269579: Pull complete 
Digest: sha256:dd10e5cd0f0fac4ae3b56f2e0e2c6f258f8244f58ce7243f22402b1a2530ec38
Status: Downloaded newer image for ldbc/datagen:latest
/opt/ldbc_snb_datagen/docker_run.sh: line 11: /opt/hadoop-2.6.0/bin/hadoop: No such file or directory
```

After building the image locally with `docker build . --tag ldbc/datagen`, the command succeeds.

**Comment by szarnyasg** [comment]
Thanks! Fixed by #98

**Comment by thSoft** [comment]
Unfortunately, this still doesn't work for me since the ldbc/datagen image hasn't been updated, only ldbc/datagen-base:

```
$ docker image rm ldbc/datagen:latest
Untagged: ldbc/datagen:latest
Deleted: sha256:88e599cc6a8d9211879d95d381c4fcb24b182b4bdad60e348fe1d5fe4e61d3c6
Deleted: sha256:1c4bd13257b5fecbf22419575673f400486a020961ce5de4235d659d9d46625e
Deleted: sha256:cf77b216870f0d2bb43c3453c53e29ab782cbba82e14c3bbf50e239a4e579e92
Deleted: sha256:8a178f4f830f50af78a06d9e22d0160be693f8e57be1fb0141053dfd7342a42c
Deleted: sha256:245141d0179fac06de13aa25775eab0274e8f9cc888961ebb7e87618382b758c
Deleted: sha256:32a9e22fae1364a7bedd1ba1e9541c5b58d856840e2ff05a5ab05c77ee780b94
Deleted: sha256:e1536ac4cf318697add7a0ee899ef739b639daf955e7ad452a148e0f1d09c6e1
Deleted: sha256:3c85853db9122858bba74632fc561e5f879e94485d2a395680d4159da47d360b
Deleted: sha256:98c8b725e411d2c4e1c4d452d13402aa07847752817ec82961a14c37bae63425
Deleted: sha256:f7780a6c228a9643e6215f735758a63abbde7a75c5b725d581b6738d5731194b
$ docker run --rm --mount type=bind,source="$(pwd)/",target="/opt/ldbc_snb_datagen/out" --mount type=bind,source="$(pwd)/params.ini",target="/opt/ldbc_snb_datagen/params.ini" ldbc/datagen
Unable to find image 'ldbc/datagen:latest' locally
latest: Pulling from ldbc/datagen
092586df9206: Pull complete 
ef599477fae0: Pull complete 
4530c6472b5d: Pull complete 
d34d61487075: Pull complete 
272f46008219: Pull complete 
12ff6ccfe7a6: Pull complete 
f26b99e1adb1: Pull complete 
6477fd664e3c: Pull complete 
309431816e80: Pull complete 
4e7b9cf72945: Pull complete 
ef94afabc02c: Pull complete 
fdb23ae508a4: Pull complete 
7e478e4997d5: Pull complete 
d02c217b7071: Pull complete 
c90f56406a3f: Pull complete 
02c8aa269579: Pull complete 
Digest: sha256:dd10e5cd0f0fac4ae3b56f2e0e2c6f258f8244f58ce7243f22402b1a2530ec38
Status: Downloaded newer image for ldbc/datagen:latest
/opt/ldbc_snb_datagen/docker_run.sh: line 11: /opt/hadoop-2.6.0/bin/hadoop: No such file or directory
```

**Comment by miratepuffin** [comment]
Hi @thSoft, sorry this was my fault. The new image should be pushed now.
